import argparse

def parse_args():
    parser = argparse.ArgumentParser(description='Model Params')
    parser.add_argument('--lr', default=1e-3, type=float, help='learning rate')
    parser.add_argument('--batch', default=4096, type=int, help='batch size')
    parser.add_argument('--test_batch', default=256, type=int, help='batch size in testset')
    parser.add_argument('--tstEpoch', default=3, type=int, help='number of epoch to test while training')
    parser.add_argument('--reg', default=1e-7, type=float, help='weight decay regularizer')
    parser.add_argument('--epoch', default=100, type=int, help='number of epochs')
    parser.add_argument('--decay', default=0.96, type=float, help='weight decay rate')
    parser.add_argument('--save_name', default='tem', help='file name to save model and training record')
    parser.add_argument('--latdim', default=32, type=int, help='embedding size')
    parser.add_argument('--load_model', default=None, help='model name to load')
    parser.add_argument('--data', default='yelp', type=str, help='name of dataset')
    parser.add_argument('--gpu', default='0', type=str, help='gpu indices')
    parser.add_argument('--patience', default='7', type=int, help='early stopping patience')
    parser.add_argument('--seed', default='1024', type=int, help='random seed')
    parser.add_argument('--gnn_layer', default=2, type=int, help='number of gnn layers')
    parser.add_argument('--topk', default=20, type=int, help='K of top K')
    return parser.parse_args()
args = parse_args()