experimentName: our
searchSpaceFile: search_space.json
trialCommand: python3 our.py --data ciao --save_name ciao_our --epoch 150
trialCodeDirectory: ../
trialConcurrency: 1
trialGpuNumber: 1
tunerGpuIndices: "0"
tuner:
  name: GridSearch
  # classArgs:
  #   optimize_mode: maximize
  #   seed: 1024
# assessor: Medianstop
trainingService: 
  platform: local
  useActiveGpu: true
  maxTrialNumberPerGpu: 4
  gpuIndices: "0"